# Generated by Django 3.2.24 on 2024-04-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perception_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback_table',
            name='rating',
            field=models.FloatField(),
        ),
    ]
