# Generated by Django 3.2.24 on 2024-04-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perception_app', '0002_alter_feedback_table_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tips_table',
            name='tips',
            field=models.CharField(max_length=500),
        ),
    ]
